// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2Khj9S_KsYc_1T-XqcYSPaoXkTecTM0',
    appId: '1:981470008330:web:b1144c0e38e30a7a2d3bf3',
    messagingSenderId: '981470008330',
    projectId: 'dtiproject-a6fa9',
    authDomain: 'dtiproject-a6fa9.firebaseapp.com',
    storageBucket: 'dtiproject-a6fa9.appspot.com',
    measurementId: 'G-QTZ4D9G63M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVsMnorT8TxNHgxBIGNbst6hxybE3oYn8',
    appId: '1:981470008330:android:47b992690a6df8a82d3bf3',
    messagingSenderId: '981470008330',
    projectId: 'dtiproject-a6fa9',
    storageBucket: 'dtiproject-a6fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6newsDyn2_7NByTjnIpgKAr7P9r1KyDM',
    appId: '1:981470008330:ios:e5517ca91e8d21112d3bf3',
    messagingSenderId: '981470008330',
    projectId: 'dtiproject-a6fa9',
    storageBucket: 'dtiproject-a6fa9.appspot.com',
    iosClientId: '981470008330-ldg1lqi8htcqp4p0nhi7jbdjn3qgs8m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6newsDyn2_7NByTjnIpgKAr7P9r1KyDM',
    appId: '1:981470008330:ios:e5517ca91e8d21112d3bf3',
    messagingSenderId: '981470008330',
    projectId: 'dtiproject-a6fa9',
    storageBucket: 'dtiproject-a6fa9.appspot.com',
    iosClientId: '981470008330-ldg1lqi8htcqp4p0nhi7jbdjn3qgs8m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.portal',
  );
}
